# This is a basic workflow to help you get started with Actions

name: update md

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    - cron: "*/60 * * * *"
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo starting workflow!

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: install python packages
        run: pip install peewee requests
      - name: run script
        run: python  main.py
        
      - name: commit
        run: |
          git config --global user.email p1ay8y3ar@gmail.com
          git config --global user.name p1ay8y3ar
          git add .
          git commit -m "update db" -a
        
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
